runtime: custom
env: flex
service: default
service_account: local-demand-intel-service@mohammad-sandbox-345817.iam.gserviceaccount.com

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 20