name: deploy default AppEngine

on:
  push:
    branches:
      - gcp_experiment

env:
  PROJECT_ID: "mohammad-sandbox-345817"

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Update requirements.txt
        run: pipenv lock -r --python 3.9 > requirements.txt

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy App Engine
        run: gcloud app deploy --quiet default.yaml --project mohammad-sandbox-345817 --promote