name: Deploy to Cloud Run

on:
  push:
    branches:
      - gcr_test

env:
  RUN_REGION: us-west1
  APP_ID: ${{github.event.repository.name}}
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Requirements
        run: pip install -r requirements.txt

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ env.SA_KEY_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
